# Generated by Django 3.0 on 2021-09-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
